import java.nio.file.FileVisitOption
import java.nio.file.Files

/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Elvarg-Game-Server"

plugins {
    id("de.fayard.refreshVersions") version("0.51.0")
}
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
include("game")
include("plugin")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            files("../gradle/libs.versions.toml")
        }
    }
}
